site_name: CelendiDocs
site_url: https://docs.celendi.xyz/
site_description: Official documentation pages for Celendi 
site_author: Team Celendi
repo_url: https://github.com/Celendi/Docs
repo_name: Celendi/Docs
edit_uri: ""
copyright: Copyright © 2022 <a target="_blank" href="https://celendi.xyz" target="_blank" rel="noopener">Team Celendi</a> • Docs Distributed under <a target="_blank" href="https://github.com/Celendi/Docs/blob/main/LICENSE" target="_blank" rel="noopener">GNU GPL v3.0</a> • <a href="#__consent">Change Cookie Settings</a>

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/Celendi_RED.png
  favicon: assets/logos/Celendi_RED.png
  icon:
    repo: fontawesome/brands/github
  
  palette:
    scheme: slate
    #primary: red # Not needed due to custom css.
  features:
    - search.suggest
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.tabs.link
    #- announce.dismiss // Disabled atm

plugins:
- search
- minify:
    minify_html: true
    htmlmin_opts:
      # https://htmlmin.readthedocs.io/en/latest/reference.html#main-functions
      remove_comments: true
      remove_all_empty_space: true
      reduce_boolean_attributes: true
      remove_optional_attribute_quotes: true
      convert_charrefs: true
    minify_css: true
    css_files:
    - assets/stylesheets/custom.css

extra:
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
- assets/stylesheets/custom.css

nav:
  - Home: index.md
  - Configuration:
    - Allow Mods: configuration/allowmods.md
    - Command Configuration: configuration/commandcfg.md
    - Command Channel: configuration/commandchannel.md
    - DMs: configuration/dms.md
    - Logs: configuration/logs.md
    - Lounge: configuration/lounge.md
    - Mod Role: configuration/modrole.md
    - Prefix: configuration/prefix.md
    - Starboard: configuration/starboard.md
    - Welcomer: configuration/welcomer.md
  - Information:
    - Information: information/information.md
  - Moderation:
    - moderation/moderation.md
  - Anime:
    - anime/anime.md
  - Fun: 
    - fun/fun.md
  - Meme:
    - meme/meme.md
  - Policies:
    - policies/terms.md
    - policies/privacy.md
    - policies/refund.md
    
markdown_extensions:
- markdown.extensions.admonition # Highlighted warning/info blocks
- markdown.extensions.attr_list # Set custom HTML attributes {: }
- markdown.extensions.footnotes # Footnotes [^1]
- markdown.extensions.meta # Define meta data (page title and description) at the top of the Markdown document
- markdown.extensions.smarty # Automatically convert dashes, underscore, three-dots and quotes to text symbols
- markdown.extensions.tables # Tables
- markdown.extensions.toc: # Add HTML id attribute to headers
    permalink: true # Headers are links to themselves
- pymdownx.betterem: # More intuitive emphasis handling
    smart_enable: all # Even smarter for both (asterisk and underscore) syntax => GitHub-like
- pymdownx.details # Collapsible details blocks
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.keys # Keyboard key symbols
- pymdownx.magiclink: # Auto-links non angle bracket URLs and email addresses and allows to shorten and visualise Git repo links
    repo_url_shortener: true
    repo_url_shorthand: true
- pymdownx.superfences # Indented code blocks, e.g. within lists, admonition, details or tabbed blocks, implies pymdownx.highlight
- pymdownx.tabbed