name: Bug Report
description: Create a report to help us improve.
title: "[Bug] "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Tell us what you see!
      value: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      description: On which OS do you have the bug?
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: On which browser do you have the bug?
    validations:
      required: true
  - type: input
    id: browserversion
    attributes:
      label: Browser version
      description: On which version of your browser do you have the bug?
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: On which device do you have the bug? Only fill this out if you're on mobile!
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false