name: Build & Deploy
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Actions:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    steps:
    - name: Clone Celendi-Docs repository
      id: clone
      # https://github.com/actions/checkout/releases
      uses: actions/checkout@v2
    - name: Setup Python for MkDocs
      id: python
      if: always() && steps.clone.outcome == 'success'
      # https://github.com/actions/setup-python/releases
      uses: actions/setup-python@v2
      with:
        # https://github.com/actions/python-versions/releases
        python-version: '3.9.10'
    - name: Install MkDocs
      id: mkdocs
      if: always() && steps.python.outcome == 'success'
      run: |
        pip3 install -U pip wheel setuptools
        pip3 install -Ur requirements.txt
    - name: Deploy Celendi-Docs
      id: deploy
      if: always() && steps.mkdocs.outcome == 'success'
      run: mkdocs gh-deploy --force
