name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  Actions:
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    steps:
    - name: Clone Celendi-Docs repository
      id: clone
      # https://github.com/actions/checkout/releases
      uses: actions/checkout@v2
    - name: Install MkDocs
      id: mkdocs
      if: always() && steps.python.outcome == 'success'
      run: |
        pip3 install -U pip wheel setuptools
        pip3 install -Ur requirements.txt
    - name: Deploy Celendi-Docs
      id: deploy
      if: always() && steps.mkdocs.outcome == 'success'
      run: mkdocs gh-deploy
